# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 5
  database: exampledb
  host: 127.0.0.1
  username: dbuser
  password: Wp123456


production: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 5
  database: production_db
  host: 127.0.0.10
  username: witspool
  password: 123456
